name: New Book Review
on:
  workflow_dispatch:
    inputs:
      book_title:
        description: 'Title'
        required: true
        type: string
      book_author:
        description: 'Author'
        required: false
        type: string
      book_link:
        description: 'Link'
        required: false
        type: string
      book_rating:
        description: 'Rating'
        required: false
        type: string
      book_review:
        description: 'Review'
        required: false
        type: string
jobs:
  new_book_review:
    name: Create new book review and open PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Dependencies
      - name: Install GSL
        run: sudo apt-get -y install libgsl-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate new book review
        env:
          BOOK_TITLE: ${{ github.event.inputs.book_title }}
          BOOK_AUTHOR: ${{ github.event.inputs.book_author }}
          BOOK_LINK: ${{ github.event.inputs.book_link }}
          BOOK_RATING: ${{ github.event.inputs.book_rating }}
          BOOK_REVIEW: ${{ github.event.inputs.book_review }}
        run: bundle exec rake new_book
      - name: Create commit
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          git add --all _books/
          git commit -m "Add book review: ${{ github.event.inputs.book_title }}"
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Add book review: ${{ github.event.inputs.book_title }}"
          body: ""
          branch-suffix: timestamp

      - name: PR Details
        run: |
          echo "- Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
