name: Tests
on:
  push:
  schedule:
    - cron: '0 7 * * *'
concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test and Publish
    runs-on: ubuntu-latest
    env:
      RUBYOPT: "--enable=yjit"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Ruby: Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bin/rspec --format documentation
      - name: Archive system spec screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: tmp/capybara/
      - name: Build website
        run: |
          bin/rails assets:precompile
          bin/parklife build
      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          enable_jekyll: false

