name: Tests
on: [push]
concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Dependencies
      - name: Install GSL
        run: sudo apt-get -y install libgsl-dev
      - name: "Ruby: Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # /Dependencies
      - name: Jekyll build
        run: bundle exec jekyll build --trace --profile --lsi
      - name: Run RSpec
        env:
          JEKYLL_SKIP_BUILD: true
        run: bundle exec rspec --format documentation
      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          enable_jekyll: false

